apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: chromium-operator
subjects:
  - kind: ServiceAccount
    namespace: "{{ .Release.Namespace }}"
    name: chromium-operator
roleRef:
  kind: ClusterRole
  name: chromium-operator
  apiGroup: rbac.authorization.k8s.io
